# Generated by Django 3.2.18 on 2023-07-26 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_priority', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('detail', models.CharField(max_length=600)),
                ('detail_feedback', models.CharField(default='null', max_length=600)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main_tickets.user')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_tickets.location')),
            ],
        ),
    ]
